preload = ~/Documents/Wallpapers/wallpaper_romantic_night_sky.jpg
preload = ~/Documents/Wallpapers/wallpaper_romantic_day_sky.jpg

wallpaper {
    monitor = DP-3 
    path = ~/Documents/Wallpapers/wallpaper_romantic_night_sky.jpg
}
wallpaper {
    monitor = DP-4
    path = ~/Documents/Wallpapers/wallpaper_romantic_day_sky.jpg
}

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
